manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/wanyann
    - name: ergohaven
      url-base: https://github.com/ergohaven
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: hold-tap-fix
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: ergohaven
      revision: eh
    - name: ergohaven-zmk-qube
      remote: ergohaven
      revision: eh
    - name: zmk-raw-hid
      remote: ergohaven
      revision: main
  self:
    path: config
